### ISSUE TITLE
Graphic function 

### ISSUE THREAD

**Issue by Qin1523** [kazuakiyama/homebrew-difmap#5] opened 2024-05-24 09:21 UTC
Hello, I met another problem when I try to use the graphic function. I'm pretty sure I have installed PGPLOT through brew. But it seems something goes wrong.
My mac version is macOS Sonoma M1, gcc14. 

```
0>uvplot 
 Graphics device/type (? to see list, default /NULL): ?
 PGPLOT v5.2.2 Copyright 1997 California Institute of Technology
 Interactive devices:
    /XWINDOW   (X window window@node:display.screen/xw)
    /XSERVE    (A /XWINDOW window that persists for re-use)
 Non-interactive file formats:
    /GIF       (Graphics Interchange Format file, landscape orientation)
    /VGIF      (Graphics Interchange Format file, portrait orientation)
    /LATEX     (LaTeX picture environment)
    /NULL      (Null device, no output)
    /PNG       (Portable Network Graphics file)
    /TPNG      (Portable Network Graphics file - transparent background)
    /PS        (PostScript file, landscape orientation)
    /VPS       (PostScript file, portrait orientation)
    /CPS       (Colour PostScript file, landscape orientation)
    /VCPS      (Colour PostScript file, portrait orientation)
 Graphics device/type (? to see list, default /NULL): /XWINDOW
PGPLOT /xw: cannot connect to X server []
 Graphics device/type (? to see list, default /NULL): /XSERVE
PGPLOT /xw: cannot connect to X server []
 Graphics device/type (? to see list, default /NULL): /XWINDOW
PGPLOT /xw: cannot connect to X server []
 Graphics device/type (? to see list, default /NULL): /xwin
PGPLOT /xw: cannot connect to X server []
 Graphics device/type (? to see list, default /NULL): /xw
PGPLOT /xw: cannot connect to X server []
```

**Comment by kazuakiyama** [comment] 2024-05-24 13:21
Hi, I couldn't reproduce this issue either in M1 or intel. As far as I saw your log, PGPLOT seems working fine. It seems to me that it didn't find a X window server. Do you have a X window system (e.g. XQuartz) installed in your macOS?

**Comment by Qin1523** [comment] 2024-05-24 16:46
I just installed XQuartz and tried to use difmap. Still the same bug.

**Comment by kazuakiyama** [comment] 2024-05-24 17:39
Can you reinstall pgplot and difmap just in case? I still don’t think this is an issue of the brew formula as I know of other users of this formula regularly using DIFMAP in a very similar environment.

**Comment by Qin1523** [comment] 2024-05-25 11:33
Hi, I tried to reinstall whole things yesterday and I failed same reason. But today when I open the difmap without any other modification, surprisingly it works. Still don't know why it comes to two different results but now I can use it. Thanks for your help.

**Comment by kazuakiyama** [comment] 2024-05-28 14:53
I'm glad that it worked now!  I will close this issue -- please feel free to reopen it if the issue occurs again.

**Closed as completed by kazuakiyama** 2024-05-28 14:53 UTC
Labels: invalid
