### ISSUE TITLE
open_index: Unable to open

### ISSUE THREAD

**Issue by Qin1523** [kazuakiyama/homebrew-difmap#4] opened 2024-05-16 23:04 UTC
Hello, my mac version is macOS Sonoma M1, gcc14. I have a problem when trying to use the difmap.
When I try to use HELP command, it comes that "open_index: Unable to open /private/tmp/difmap-20240516-20455-p3h75u/uvf_difmap_2.5q/help/maths.idx." 

```
Caltech difference mapping program - version 2.5q (3 Dec 2022)
Copyright (c) 1993-2022 California Institute of Technology. All Rights Reserved.
Type 'help difmap' to list difference mapping commands and help topics.
Started logfile: difmap.log on Fri May 17 00:54:28 2024
0>help
List of function modules.
	difmap
	file_io
	general
	graphics
	maths
For more help, type HELP module_name or HELP function_name.
0>help maths
open_index: Unable to open /private/tmp/difmap-20240516-20455-p3h75u/uvf_difmap_2.5q/help/maths.idx.
open_index: Use the 'makeindex' command.

Help available for module: maths
Listing completed.
```

**Comment by kazuakiyama** [comment] 2024-05-17 03:48
This seems to be an easy fix as this is simply an issue of the path to help files. The current specified location in your error log seems a temporary directory only used in `brew install difmap`.  Let me take a look at tomorrow. I will keep you posted.

**Comment by kazuakiyama** [comment] 2024-05-17 20:40
It turns out that this issue has been there since from the beginning of this repository because I erroneously didn't set up the installation in a way to install all entire help files to the brew's prefix directory for difmap. Also the recent fix for issue #3 further corrupted this issue from another point (which I mentioned in my previous response). 

Both of them are now fixed. Please try out Rev 5 formula (2.5p_5). You can simply do by `brew update; brew upgrade difmap`. 

Thanks for pointing this out. I would never have found this issue by myself.

**Comment by kazuakiyama** [comment] 2024-05-17 20:46
I will close this issue as I confirmed the fix in both apple silicon and intel mac. Please feel free to reopen if the issue still persists on your end.

**Closed by kazuakiyama** 2024-05-17 20:46 UTC
Labels: bug

**Comment by Qin1523** [comment] 2024-05-17 20:52
Thanks a lot! It works!

**Comment by kazuakiyama** [comment] 2024-05-17 20:53
Great! Enjoy!
