### ISSUE TITLE
Installation issue on Intel MacOS Sequlia 15.0.1

### ISSUE THREAD

**Issue by Niu-Liu** [kazuakiyama/homebrew-difmap#6] opened 2024-10-17 04:39 UTC
Hi Akiyama san,

Thank you for providing a very convenient way for installing difmap, which makes many Difmap users' life easier. 

I encountered an issue while trying to install difmap. The error messages are shown below while the [log files](https://github.com/user-attachments/files/17406101/difmap_installation.tar.gz) are attached.
I also downloaded the source pacakge and compiled it, which did not return this error message. It succeeded in compiling libpager.a. Instead, it returned an error message similar to [issue#3](https://github.com/kazuakiyama/homebrew-difmap/issues/3). Passing an argument "-Wno-error=incompatible-pointer-types" to CFLAGS would not help for my case.

Do you have anysuggestions?

Best regards,
Niu

----------------------------- ERROR MESSAGE -------------------------------------------------
==> Applying patch_difmap2.5q_configure.diff
patching file configure
==> Using Homebrew-provided Fortran compiler
This may be changed by setting the FC environment variable.
==> ./configure intel-osx-gcc
==> ./makeall
Last 15 lines from /Users/Neo/Library/Logs/Homebrew/difmap/02.makeall:
    1 | #ifndef sphere_h
sphere.h:176:18: error: unknown type name 'FILE'
  176 | int push_command(FILE *fp, const char *comstr, const char *filename,
      |                  ^~~~
sphere.h:176:18: note: 'FILE' is defined in header '<stdio.h>'; this is probably fixable by adding '#include <stdio.h>'
In file included from compile.c:14:
help.h:4:10: fatal error: pager.h: No such file or directory
    4 | #include "pager.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [compile.o] Error 1

Compiling difmap itself

make: *** No rule to make target `/private/tmp/difmap-20241017-44801-jdbt1o/uvf_difmap_2.5q/include/logio.h', needed by `startup.o'.  Stop.

--------------------------------- ERROR MESSAGE ---------------------------------------------

**Comment by kazuakiyama** [comment] 2024-10-17 17:21
Thanks for the issue. I don't have Sequoia in local environments as our institute recommends *against* installing it for now because it provides many breaking changes in our software ecosystem. So in the mean time I can't reproduce the results. 

Anyway, this seems to be a similar issue with the previous one. I think probably an origin is that some issues ignored or handled ok implicitly in previous compilers are flagged as errors in the latest Xcode environment after macOS 15. I will explore issue but it would take a time as I'm busy next few weeks for other commitments. 

In the mean time, I have a separate question. You are apparently using intel machine for your macOS 15. Did you encounter this issue in PGPLOT, when you installed PGPLOT?
https://github.com/kazuakiyama/homebrew-pgplot/issues/6

**Comment by kazuakiyama** [comment] 2024-10-17 17:27
Ok, I confirmed that the formula still works for macOS 14 in both intel and Apple Silicon architecture. I will explore any way to test it in a newer macOS. Sorry that I can't offer immediate help. Keep you posted about the issue.

**Comment by Niu-Liu** [comment] 2024-10-17 17:59
Thank you for the reply. I successfully installed PGPLOT and SCHED via your repository. It was really a bad idea to upgrade to a new OS :-(

Thank you for the help. I can use my server (Ubuntu) instead.

**Comment by Niu-Liu** [comment] 2024-11-11 21:54
Hi Akiyama-san,

Just wanted to share some good news: today I patched the diff file in your repository and manually compiled the code—it worked! After upgrading macOS to Sequoia 15.1, I retried installing Difmap via `brew install difmap` and that also succeeded.

Thanks again for your support.

**Comment by kazuakiyama** [comment] 2024-11-11 23:14
@Niu-Liu 
Thanks for the heads up! Glad to hear that the issue has spontaneously resolved. Yes, sometimes waiting for the first few minor revisions often helps with issues with a newly released macOS. I think this was due to an aggressive change in some specs of the native C compiler, which might be fixed with 15.1. 

I will close the issue for now. Please feel free to open when you find a similar issue.

**Closed as completed by kazuakiyama** 2024-11-11 23:14 UTC
Labels: bug
